// Starbucks Nutrition Data
// This data represents a comprehensive database of Starbucks menu items and customizations

export interface NutritionInfo {
  calories: number;
  fat: number;
  carbs: number;
  protein: number;
  sugar: number;
  caffeine: number;
  sodium: number;
}

export interface Product extends NutritionInfo {
  id: string;
  name: string;
  category: "hot" | "cold" | "frappe" | "food" | "bakery" | "snacks";
  size: "short" | "tall" | "grande" | "venti";
  sizeLabel: string;
  defaultCustomizations: Record<string, number>;
}

export interface Customization extends NutritionInfo {
  id: string;
  name: string;
  type: "milk" | "syrup" | "sauce" | "topping" | "foam" | "drizzle" | "powder" | "espresso" | "sweetener";
  unit: string;
  replacementFor?: string;
}

// Sample Starbucks Products - Hot Drinks
export const hotProducts: Product[] = [
  {
    id: "caffe-americano",
    name: "Caffè Americano",
    category: "hot",
    size: "short",
    sizeLabel: "Short (8 fl oz)",
    calories: 15,
    fat: 0,
    carbs: 1,
    protein: 1,
    sugar: 0,
    caffeine: 75,
    sodium: 5,
    defaultCustomizations: { "espresso-shot": 3 },
  },
  {
    id: "caffe-americano-tall",
    name: "Caffè Americano",
    category: "hot",
    size: "tall",
    sizeLabel: "Tall (12 fl oz)",
    calories: 15,
    fat: 0,
    carbs: 1,
    protein: 1,
    sugar: 0,
    caffeine: 150,
    sodium: 10,
    defaultCustomizations: { "espresso-shot": 3 },
  },
  {
    id: "caffe-americano-grande",
    name: "Caffè Americano",
    category: "hot",
    size: "grande",
    sizeLabel: "Grande (16 fl oz)",
    calories: 15,
    fat: 0,
    carbs: 1,
    protein: 1,
    sugar: 0,
    caffeine: 225,
    sodium: 15,
    defaultCustomizations: { "espresso-shot": 3 },
  },
  {
    id: "caffe-americano-venti",
    name: "Caffè Americano",
    category: "hot",
    size: "venti",
    sizeLabel: "Venti (20 fl oz)",
    calories: 20,
    fat: 0,
    carbs: 1,
    protein: 2,
    sugar: 0,
    caffeine: 300,
    sodium: 20,
    defaultCustomizations: { "espresso-shot": 4 },
  },
  {
    id: "pike-place-roast",
    name: "Pike Place Roast",
    category: "hot",
    size: "short",
    sizeLabel: "Short (8 fl oz)",
    calories: 3,
    fat: 0,
    carbs: 0,
    protein: 0,
    sugar: 0,
    caffeine: 155,
    sodium: 0,
    defaultCustomizations: {},
  },
  {
    id: "pike-place-roast-tall",
    name: "Pike Place Roast",
    category: "hot",
    size: "tall",
    sizeLabel: "Tall (12 fl oz)",
    calories: 5,
    fat: 0,
    carbs: 1,
    protein: 1,
    sugar: 0,
    caffeine: 235,
    sodium: 5,
    defaultCustomizations: {},
  },
  {
    id: "pike-place-roast-grande",
    name: "Pike Place Roast",
    category: "hot",
    size: "grande",
    sizeLabel: "Grande (16 fl oz)",
    calories: 5,
    fat: 0,
    carbs: 1,
    protein: 1,
    sugar: 0,
    caffeine: 310,
    sodium: 10,
    defaultCustomizations: {},
  },
  {
    id: "pike-place-roast-venti",
    name: "Pike Place Roast",
    category: "hot",
    size: "venti",
    sizeLabel: "Venti (20 fl oz)",
    calories: 10,
    fat: 0,
    carbs: 2,
    protein: 1,
    sugar: 0,
    caffeine: 410,
    sodium: 10,
    defaultCustomizations: {},
  },
  {
    id: "caffe-latte",
    name: "Caffè Latte",
    category: "hot",
    size: "short",
    sizeLabel: "Short (8 fl oz)",
    calories: 150,
    fat: 6,
    carbs: 12,
    protein: 11,
    sugar: 9,
    caffeine: 75,
    sodium: 150,
    defaultCustomizations: { "espresso-shot": 1, "milk": 1 },
  },
  {
    id: "caffe-latte-tall",
    name: "Caffè Latte",
    category: "hot",
    size: "tall",
    sizeLabel: "Tall (12 fl oz)",
    calories: 190,
    fat: 7,
    carbs: 18,
    protein: 13,
    sugar: 17,
    caffeine: 75,
    sodium: 160,
    defaultCustomizations: { "espresso-shot": 1, "milk": 1 },
  },
  {
    id: "caffe-latte-grande",
    name: "Caffè Latte",
    category: "hot",
    size: "grande",
    sizeLabel: "Grande (16 fl oz)",
    calories: 240,
    fat: 9,
    carbs: 24,
    protein: 16,
    sugar: 22,
    caffeine: 150,
    sodium: 200,
    defaultCustomizations: { "espresso-shot": 2, "milk": 1 },
  },
  {
    id: "caffe-latte-venti",
    name: "Caffè Latte",
    category: "hot",
    size: "venti",
    sizeLabel: "Venti (20 fl oz)",
    calories: 310,
    fat: 11,
    carbs: 32,
    protein: 21,
    sugar: 30,
    caffeine: 150,
    sodium: 260,
    defaultCustomizations: { "espresso-shot": 2, "milk": 1 },
  },
  {
    id: "caramel-macchiato",
    name: "Caramel Macchiato",
    category: "hot",
    size: "short",
    sizeLabel: "Short (8 fl oz)",
    calories: 150,
    fat: 5,
    carbs: 23,
    protein: 9,
    sugar: 22,
    caffeine: 75,
    sodium: 75,
    defaultCustomizations: { "espresso-shot": 1, "milk": 1, "caramel-drizzle": 1 },
  },
  {
    id: "caramel-macchiato-tall",
    name: "Caramel Macchiato",
    category: "hot",
    size: "tall",
    sizeLabel: "Tall (12 fl oz)",
    calories: 240,
    fat: 8,
    carbs: 35,
    protein: 12,
    sugar: 34,
    caffeine: 75,
    sodium: 120,
    defaultCustomizations: { "espresso-shot": 1, "milk": 1, "caramel-drizzle": 1 },
  },
  {
    id: "caramel-macchiato-grande",
    name: "Caramel Macchiato",
    category: "hot",
    size: "grande",
    sizeLabel: "Grande (16 fl oz)",
    calories: 300,
    fat: 10,
    carbs: 43,
    protein: 15,
    sugar: 41,
    caffeine: 150,
    sodium: 150,
    defaultCustomizations: { "espresso-shot": 2, "milk": 1, "caramel-drizzle": 1 },
  },
  {
    id: "caramel-macchiato-venti",
    name: "Caramel Macchiato",
    category: "hot",
    size: "venti",
    sizeLabel: "Venti (20 fl oz)",
    calories: 380,
    fat: 13,
    carbs: 54,
    protein: 19,
    sugar: 52,
    caffeine: 150,
    sodium: 190,
    defaultCustomizations: { "espresso-shot": 2, "milk": 1, "caramel-drizzle": 1 },
  },
];

// Sample Cold Drinks
export const coldProducts: Product[] = [
  {
    id: "iced-caffe-americano",
    name: "Iced Caffè Americano",
    category: "cold",
    size: "tall",
    sizeLabel: "Tall (12 fl oz)",
    calories: 15,
    fat: 0,
    carbs: 1,
    protein: 1,
    sugar: 0,
    caffeine: 150,
    sodium: 10,
    defaultCustomizations: { "espresso-shot": 3 },
  },
  {
    id: "iced-caffe-americano-grande",
    name: "Iced Caffè Americano",
    category: "cold",
    size: "grande",
    sizeLabel: "Grande (16 fl oz)",
    calories: 15,
    fat: 0,
    carbs: 1,
    protein: 1,
    sugar: 0,
    caffeine: 225,
    sodium: 15,
    defaultCustomizations: { "espresso-shot": 3 },
  },
  {
    id: "iced-caffe-americano-venti",
    name: "Iced Caffè Americano",
    category: "cold",
    size: "venti",
    sizeLabel: "Venti (20 fl oz)",
    calories: 20,
    fat: 0,
    carbs: 1,
    protein: 2,
    sugar: 0,
    caffeine: 300,
    sodium: 20,
    defaultCustomizations: { "espresso-shot": 4 },
  },
  {
    id: "iced-caffe-latte",
    name: "Iced Caffè Latte",
    category: "cold",
    size: "tall",
    sizeLabel: "Tall (12 fl oz)",
    calories: 130,
    fat: 5,
    carbs: 12,
    protein: 10,
    sugar: 11,
    caffeine: 75,
    sodium: 150,
    defaultCustomizations: { "espresso-shot": 1, "milk": 1 },
  },
  {
    id: "iced-caffe-latte-grande",
    name: "Iced Caffè Latte",
    category: "cold",
    size: "grande",
    sizeLabel: "Grande (16 fl oz)",
    calories: 170,
    fat: 6,
    carbs: 17,
    protein: 13,
    sugar: 16,
    caffeine: 150,
    sodium: 200,
    defaultCustomizations: { "espresso-shot": 2, "milk": 1 },
  },
];

// Customizations Database
export const customizations: Customization[] = [
  // Milk Options
  {
    id: "milk-2percent",
    name: "2% Milk",
    type: "milk",
    unit: "splash",
    replacementFor: "default-milk",
    calories: 20,
    fat: 1,
    carbs: 2,
    protein: 2,
    sugar: 2,
    caffeine: 0,
    sodium: 25,
  },
  {
    id: "milk-whole",
    name: "Whole Milk",
    type: "milk",
    unit: "splash",
    replacementFor: "default-milk",
    calories: 35,
    fat: 2,
    carbs: 2,
    protein: 2,
    sugar: 2,
    caffeine: 0,
    sodium: 20,
  },
  {
    id: "milk-almond",
    name: "Almond Milk",
    type: "milk",
    unit: "splash",
    replacementFor: "default-milk",
    calories: 10,
    fat: 1,
    carbs: 1,
    protein: 0,
    sugar: 0,
    caffeine: 0,
    sodium: 170,
  },
  {
    id: "milk-oat",
    name: "Oatmilk",
    type: "milk",
    unit: "splash",
    replacementFor: "default-milk",
    calories: 25,
    fat: 1,
    carbs: 3,
    protein: 1,
    sugar: 1,
    caffeine: 0,
    sodium: 75,
  },
  {
    id: "milk-coconut",
    name: "Coconut Milk",
    type: "milk",
    unit: "splash",
    replacementFor: "default-milk",
    calories: 15,
    fat: 1,
    carbs: 1,
    protein: 0,
    sugar: 1,
    caffeine: 0,
    sodium: 10,
  },
  {
    id: "milk-breve",
    name: "Breve (Half and Half)",
    type: "milk",
    unit: "splash",
    replacementFor: "default-milk",
    calories: 40,
    fat: 4,
    carbs: 1,
    protein: 1,
    sugar: 1,
    caffeine: 0,
    sodium: 10,
  },
  // Syrups
  {
    id: "syrup-vanilla",
    name: "Vanilla Syrup",
    type: "syrup",
    unit: "pump",
    calories: 20,
    fat: 0,
    carbs: 5,
    protein: 0,
    sugar: 5,
    caffeine: 0,
    sodium: 0,
  },
  {
    id: "syrup-caramel",
    name: "Caramel Syrup",
    type: "syrup",
    unit: "pump",
    calories: 20,
    fat: 0,
    carbs: 5,
    protein: 0,
    sugar: 5,
    caffeine: 0,
    sodium: 0,
  },
  {
    id: "syrup-hazelnut",
    name: "Hazelnut Syrup",
    type: "syrup",
    unit: "pump",
    calories: 20,
    fat: 0,
    carbs: 5,
    protein: 0,
    sugar: 5,
    caffeine: 0,
    sodium: 0,
  },
  {
    id: "syrup-brown-sugar",
    name: "Brown Sugar Syrup",
    type: "syrup",
    unit: "pump",
    calories: 20,
    fat: 0,
    carbs: 5,
    protein: 0,
    sugar: 5,
    caffeine: 0,
    sodium: 0,
  },
  {
    id: "syrup-pumpkin",
    name: "Pumpkin Syrup",
    type: "syrup",
    unit: "pump",
    calories: 20,
    fat: 0,
    carbs: 5,
    protein: 0,
    sugar: 5,
    caffeine: 0,
    sodium: 0,
  },
  // Sauces
  {
    id: "sauce-mocha",
    name: "Mocha Sauce",
    type: "sauce",
    unit: "pump",
    calories: 25,
    fat: 1,
    carbs: 4,
    protein: 1,
    sugar: 3,
    caffeine: 5,
    sodium: 10,
  },
  {
    id: "sauce-caramel-brulee",
    name: "Caramel Brulée Sauce",
    type: "sauce",
    unit: "pump",
    calories: 30,
    fat: 1,
    carbs: 6,
    protein: 0,
    sugar: 6,
    caffeine: 0,
    sodium: 5,
  },
  {
    id: "sauce-white-mocha",
    name: "White Chocolate Mocha Sauce",
    type: "sauce",
    unit: "pump",
    calories: 35,
    fat: 1,
    carbs: 6,
    protein: 1,
    sugar: 6,
    caffeine: 0,
    sodium: 15,
  },
  // Toppings
  {
    id: "topping-whipped-cream",
    name: "Whipped Cream",
    type: "topping",
    unit: "regular",
    calories: 50,
    fat: 5,
    carbs: 2,
    protein: 0,
    sugar: 2,
    caffeine: 0,
    sodium: 10,
  },
  {
    id: "topping-caramel-drizzle",
    name: "Caramel Drizzle",
    type: "drizzle",
    unit: "regular",
    calories: 15,
    fat: 0,
    carbs: 4,
    protein: 0,
    sugar: 4,
    caffeine: 0,
    sodium: 0,
  },
  {
    id: "topping-mocha-drizzle",
    name: "Mocha Drizzle",
    type: "drizzle",
    unit: "regular",
    calories: 20,
    fat: 1,
    carbs: 3,
    protein: 0,
    sugar: 3,
    caffeine: 5,
    sodium: 5,
  },
  {
    id: "topping-cinnamon",
    name: "Cinnamon Powder",
    type: "powder",
    unit: "sprinkle",
    calories: 0,
    fat: 0,
    carbs: 0,
    protein: 0,
    sugar: 0,
    caffeine: 0,
    sodium: 0,
  },
  // Espresso Shots
  {
    id: "espresso-shot",
    name: "Espresso Shot",
    type: "espresso",
    unit: "shot",
    calories: 5,
    fat: 0,
    carbs: 0,
    protein: 0,
    sugar: 0,
    caffeine: 75,
    sodium: 0,
  },
  {
    id: "espresso-shot-extra",
    name: "Extra Espresso Shot",
    type: "espresso",
    unit: "shot",
    calories: 5,
    fat: 0,
    carbs: 0,
    protein: 0,
    sugar: 0,
    caffeine: 75,
    sodium: 0,
  },
];

// Helper function to get all products
export function getAllProducts(): Product[] {
  return [...hotProducts, ...coldProducts];
}

// Helper function to get products by category
export function getProductsByCategory(category: string): Product[] {
  const allProducts = getAllProducts();
  return allProducts.filter((p) => p.category === category);
}

// Helper function to get customization by ID
export function getCustomizationById(id: string): Customization | undefined {
  return customizations.find((c) => c.id === id);
}

// Helper function to get customizations by type
export function getCustomizationsByType(type: string): Customization[] {
  return customizations.filter((c) => c.type === type);
}
